### ISSUE TITLE
Floating PDF after loading

### ISSUE THREAD

**Issue by InteractiveLogic** [vfr/Reader#121]
I'm seeing a strange effect after loading up a PDF document in my app, which is exclusively iPad and exclusively landscape. 

After loading the document, instead of scrolling horizontally only, it scrolls vertically in the container. This is a very bizarre user experience since the document "floats" in the space a bit then centers (like it's on the moon.).

In the absence of a fix or property to turn off zooming, I turned off Bounces and BouncesZoom and that _seems_ to help a bit, except for the vertical position adjustment with the status bar that happens periodically.

But for now, this works and it will have to do... I just wanted to bring it to your attention since it was pretty weird.

Thanks for saving me tons of time to develop this, however! It's a great PDF reader!

**Comment by VrasidasP** [comment]
I've seen strange animations like this when I've used
[UIView beginAnimations:@"animations" context:@"context"];
without a corresponding [UIView commitAnimations];
(because I forgot to add it or commented it).

Check your code to see if there is anything like that (even in seemingly unrelated view controllers)
